### ISSUE TITLE
ansible-galaxy is not working with this role

### ISSUE THREAD

**Issue by letac** [ElaoInfra/ansible-role-grafana#3]
master branch does not exist, but ansible-galaxy is trying to download https://github.com/ElaoInfra/ansible-role-grafana/archive/master.tar.gz

**Comment by nervo** [comment]
Ooops, we forgot to specify the version in the installation instructions, sorry

See https://github.com/ElaoInfra/ansible-role-grafana/commit/65af23f94322126f4bbb92cb349a9df3e7201c4f
